apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ticket-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: samimms/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        - name: DATABASE_URL
          value: "mongodb://mongodb-auth:27017/auth_db"
        - name: RABBITMQ_URL
          value: "amqp://admin:admin@rabbitmq:5672"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: JWT_EXPIRES_IN
          value: "1d"
        - name: ADMIN_FRONTEND
          value: "http://localhost:8081"
        - name: ADMIN_BACKEND
          value: "http://localhost:3001"
        - name: CUSTOMER_FRONTEND
          value: "http://localhost:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ticket-system
spec:
  selector:
    app: auth-service
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-backend
  namespace: ticket-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-backend
  template:
    metadata:
      labels:
        app: admin-backend
    spec:
      containers:
      - name: admin-backend
        image: samimms/admin-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "development"
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "ticket_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user-password
        - name: DB_NAME
          value: "ticket_system"
        - name: RABBITMQ_URL
          value: "amqp://admin:admin@rabbitmq:5672"
        - name: LOCAL_ENV
          value: "http://localhost:8081"
        - name: ADMIN_FRONTEND
          value: "http://localhost:8081"
        - name: AUTH_URL
          value: "http://auth-service:3000"
        - name: ADMIN_BACKEND_PORT
          value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-backend
  namespace: ticket-system
spec:
  selector:
    app: admin-backend
  ports:
  - port: 3001
    targetPort: 3001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-backend
  namespace: ticket-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-backend
  template:
    metadata:
      labels:
        app: customer-backend
    spec:
      containers:
      - name: customer-backend
        image: samimms/customer-backend:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "development"
        - name: DATABASE_URL
          value: "mongodb://mongodb:27017/customer_db"
        - name: RABBITMQ_URL
          value: "amqp://admin:admin@rabbitmq:5672"
        - name: CUSTOMER_BACKEND_PORT
          value: "3002"
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-secret
              key: STRIPE_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: customer-backend
  namespace: ticket-system
spec:
  selector:
    app: customer-backend
  ports:
  - port: 3002
    targetPort: 3002
  type: LoadBalancer 