name: Build, Push and Deploy a Docker Image to DigitalOcean

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DigitalOcean container registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: samimsaidi
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/dls/myapp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max