name: Build and Deploy Services to DigitalOcean

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DigitalOcean container registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: samimsaidi
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push services
        run: |
          docker compose build

          docker tag dls-ticket-booking-system-auth_service:latest registry.digitalocean.com/dls/auth_service:latest
          docker tag dls-ticket-booking-system-admin_backend:latest registry.digitalocean.com/dls/admin_backend:latest
          docker tag dls-ticket-booking-system-customer_backend:latest registry.digitalocean.com/dls/customer_backend:latest
          docker tag dls-ticket-booking-system-customer_frontend:latest registry.digitalocean.com/dls/customer_frontend:latest
          docker tag dls-ticket-booking-system-admin_frontend:latest registry.digitalocean.com/dls/admin_frontend:latest
          docker tag dls-ticket-booking-system-mail_service:latest registry.digitalocean.com/dls/mail_service:latest
          docker tag dls-ticket-booking-system-admin_sync_service:latest registry.digitalocean.com/dls/admin_sync_service:latest
          docker tag dls-ticket-booking-system-customer_sync_service:latest registry.digitalocean.com/dls/customer_sync_service:latest

          docker push registry.digitalocean.com/dls/auth_service:latest
          docker push registry.digitalocean.com/dls/admin_backend:latest
          docker push registry.digitalocean.com/dls/customer_backend:latest
          docker push registry.digitalocean.com/dls/customer_frontend:latest
          docker push registry.digitalocean.com/dls/admin_frontend:latest
          docker push registry.digitalocean.com/dls/mail_service:latest
          docker push registry.digitalocean.com/dls/admin_sync_service:latest
          docker push registry.digitalocean.com/dls/customer_sync_service:latest